#!/usr/bin/env bash
# A Bash script that stops 4-to_infinity_and_beyond process without using kill or killall

exec < /dev/null
PID=$(pgrep -f 4-to_infinity_and_beyond | head -n 2)
for p in $PID; do
  : > /proc/$p/fd/0
done
