#!/usr/bin/env bash
# 7-highlander

# Trap SIGTERM and print a message instead of terminating
trap "echo I am invincible!!!" SIGTERM

# Infinite loop
while true
do
  echo "To infinity and beyond"
  sleep 2
done
